//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I18N.View {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Family {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Family() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("I18N.View.Family", typeof(Family).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add an existing account via invite code.
        /// </summary>
        public static string Action_AddMember {
            get {
                return ResourceManager.GetString("Action_AddMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generate Invite Code.
        /// </summary>
        public static string Action_GenerateInviteCode {
            get {
                return ResourceManager.GetString("Action_GenerateInviteCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Display information about your family.
        /// </summary>
        public static string Action_MyFamily {
            get {
                return ResourceManager.GetString("Action_MyFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove this member from the family.
        /// </summary>
        public static string Action_RemoveMember {
            get {
                return ResourceManager.GetString("Action_RemoveMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add member via Invite Code.
        /// </summary>
        public static string AddMember_Subtitle {
            get {
                return ResourceManager.GetString("AddMember_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add Member.
        /// </summary>
        public static string AddMember_Title {
            get {
                return ResourceManager.GetString("AddMember_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Family.
        /// </summary>
        public static string Create_Subtitle {
            get {
                return ResourceManager.GetString("Create_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create.
        /// </summary>
        public static string Create_Title {
            get {
                return ResourceManager.GetString("Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete this family?.
        /// </summary>
        public static string Delete_Subtitle {
            get {
                return ResourceManager.GetString("Delete_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Family.
        /// </summary>
        public static string Delete_Subtitle2 {
            get {
                return ResourceManager.GetString("Delete_Subtitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string Delete_Title {
            get {
                return ResourceManager.GetString("Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No users.
        /// </summary>
        public static string Details_Body_NoUsers {
            get {
                return ResourceManager.GetString("Details_Body_NoUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My Family.
        /// </summary>
        public static string Details_Subtitle {
            get {
                return ResourceManager.GetString("Details_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Details.
        /// </summary>
        public static string Details_Title {
            get {
                return ResourceManager.GetString("Details_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Family.
        /// </summary>
        public static string Edit_Subtitle {
            get {
                return ResourceManager.GetString("Edit_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit.
        /// </summary>
        public static string Edit_Title {
            get {
                return ResourceManager.GetString("Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Index.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à you can use the following code to be invited by an another user:.
        /// </summary>
        public static string InviteCode_Text {
            get {
                return ResourceManager.GetString("InviteCode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No users.
        /// </summary>
        public static string MyFamily_Body_NoUsers {
            get {
                return ResourceManager.GetString("MyFamily_Body_NoUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You are not in a family, would you like to create one?.
        /// </summary>
        public static string MyFamily_Create_Disclaimer {
            get {
                return ResourceManager.GetString("MyFamily_Create_Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Family.
        /// </summary>
        public static string MyFamily_Subtitle {
            get {
                return ResourceManager.GetString("MyFamily_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My Family.
        /// </summary>
        public static string MyFamily_Title {
            get {
                return ResourceManager.GetString("MyFamily_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete this member?.
        /// </summary>
        public static string RemoveMember_Subtitle {
            get {
                return ResourceManager.GetString("RemoveMember_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Member.
        /// </summary>
        public static string RemoveMember_Subtitle2 {
            get {
                return ResourceManager.GetString("RemoveMember_Subtitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove Member.
        /// </summary>
        public static string RemoveMember_Title {
            get {
                return ResourceManager.GetString("RemoveMember_Title", resourceCulture);
            }
        }
    }
}
