//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebApplication {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebApplication() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("I18N.WebApplication", typeof(WebApplication).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application description page..
        /// </summary>
        public static string About_Subtitle {
            get {
                return ResourceManager.GetString("About_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coaches:.
        /// </summary>
        public static string Constitution_Coaches {
            get {
                return ResourceManager.GetString("Constitution_Coaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must guide the young sports people in their charge to move forward in fitness, skill, and understanding of sport.  Coaches must develop the members’ appreciation for surfing and the ocean. A successful season can be measured by the amount the participants move forward, by the quality of their effort, and by their joy in participating. Wins and losses fall where they may, but hopefully they’ve learned to love to be active..
        /// </summary>
        public static string Constitution_Coaches_Text {
            get {
                return ResourceManager.GetString("Constitution_Coaches_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respect the rights, dignity and worth of others;.
        /// </summary>
        public static string Constitution_CodeOfConduct_Li1 {
            get {
                return ResourceManager.GetString("Constitution_CodeOfConduct_Li1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be fair, equitable, considerate and honest in all Dealings with others..
        /// </summary>
        public static string Constitution_CodeOfConduct_Li2 {
            get {
                return ResourceManager.GetString("Constitution_CodeOfConduct_Li2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be professional in, and accept responsibility for actions;.
        /// </summary>
        public static string Constitution_CodeOfConduct_Li3 {
            get {
                return ResourceManager.GetString("Constitution_CodeOfConduct_Li3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use facilities and equipment for their proper purposes, and care for and maintain such facilities and equipment correctly;.
        /// </summary>
        public static string Constitution_CodeOfConduct_Li4 {
            get {
                return ResourceManager.GetString("Constitution_CodeOfConduct_Li4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refrain from anything which may abuse, intimidate or harass others;.
        /// </summary>
        public static string Constitution_CodeOfConduct_Li5 {
            get {
                return ResourceManager.GetString("Constitution_CodeOfConduct_Li5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preserve and protect the standing and reputation of the County Sligo Surf Club;.
        /// </summary>
        public static string Constitution_CodeOfConduct_Li6 {
            get {
                return ResourceManager.GetString("Constitution_CodeOfConduct_Li6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Understand the consequences of any breach of County Sligo Surf Club’s Member Protection Policy or Code of Conduct; ***.
        /// </summary>
        public static string Constitution_CodeOfConduct_Li7 {
            get {
                return ResourceManager.GetString("Constitution_CodeOfConduct_Li7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The County Sligo Surf Club  is committed to providing a Fair Play sporting environment in which all individuals involved are treated with dignity and respect. Every participant’s experience should be positive; all participants should have an opportunity to contribute and every participant should experience success. Our sports programs encourage participation in the joy of the sport and the learning of good sportsmanship and appreciation for the ocean..
        /// </summary>
        public static string Constitution_FairPlayPolicy1 {
            get {
                return ResourceManager.GetString("Constitution_FairPlayPolicy1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The County Sligo Surf Club has a zero tolerance policy regarding harassment: generally defined as comment, conduct, or gesture directed toward an individual or group of individuals, which is insulting, intimidating, humiliating, malicious, degrading, or offensive..
        /// </summary>
        public static string Constitution_FairPlayPolicy2 {
            get {
                return ResourceManager.GetString("Constitution_FairPlayPolicy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The County Sligo Surf Club believes in catering to the needs of all children and young people, from beginners to the most proficient. Special provisions may be required for children and young people who are disadvantaged or whose participation is limited for any reason..
        /// </summary>
        public static string Constitution_FairPlayPolicy3 {
            get {
                return ResourceManager.GetString("Constitution_FairPlayPolicy3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep sport fun – it’s why we do it.
        /// </summary>
        public static string Constitution_KeepSportFun {
            get {
                return ResourceManager.GetString("Constitution_KeepSportFun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parents:.
        /// </summary>
        public static string Constitution_Parents {
            get {
                return ResourceManager.GetString("Constitution_Parents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encourage children in their efforts in sport.
        /// </summary>
        public static string Constitution_Parents_Li1 {
            get {
                return ResourceManager.GetString("Constitution_Parents_Li1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember that we are all capable of making mistakes.
        /// </summary>
        public static string Constitution_Parents_Li10 {
            get {
                return ResourceManager.GetString("Constitution_Parents_Li10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treat my child the same regardless of whether she/he has won or lost.
        /// </summary>
        public static string Constitution_Parents_Li2 {
            get {
                return ResourceManager.GetString("Constitution_Parents_Li2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch my child play and let him/her enjoy the sport.
        /// </summary>
        public static string Constitution_Parents_Li3 {
            get {
                return ResourceManager.GetString("Constitution_Parents_Li3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show my appreciation to people who volunteer their time so my child can play.
        /// </summary>
        public static string Constitution_Parents_Li4 {
            get {
                return ResourceManager.GetString("Constitution_Parents_Li4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember that my child plays sport for his/her reasons not mine.
        /// </summary>
        public static string Constitution_Parents_Li5 {
            get {
                return ResourceManager.GetString("Constitution_Parents_Li5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be a positive role model for my child.
        /// </summary>
        public static string Constitution_Parents_Li6 {
            get {
                return ResourceManager.GetString("Constitution_Parents_Li6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never place undue pressure on my child to play or perform.
        /// </summary>
        public static string Constitution_Parents_Li7 {
            get {
                return ResourceManager.GetString("Constitution_Parents_Li7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respect that people are involved in sport mostly for fun and enjoyment.
        /// </summary>
        public static string Constitution_Parents_Li8 {
            get {
                return ResourceManager.GetString("Constitution_Parents_Li8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support good play and applaud good performance from all participants.
        /// </summary>
        public static string Constitution_Parents_Li9 {
            get {
                return ResourceManager.GetString("Constitution_Parents_Li9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Constitution and Policies.
        /// </summary>
        public static string Constitution_Title {
            get {
                return ResourceManager.GetString("Constitution_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CODE OF CONDUCT FOR MEMBERS.
        /// </summary>
        public static string Constitution_Title_CodeOfConduct {
            get {
                return ResourceManager.GetString("Constitution_Title_CodeOfConduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAIR PLAY POLICY – County Sligo Surf Club Code of Conduct.
        /// </summary>
        public static string Constitution_Title_FairPlayPolicy {
            get {
                return ResourceManager.GetString("Constitution_Title_FairPlayPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** County Sligo Surf Club, (sitting committee) reserves the right to terminate a membership, or enact a three strikes policy towards any member who fails to adhere to County Sligo Surf Club’s Code of Conduct..
        /// </summary>
        public static string Constitution_TripleStars {
            get {
                return ResourceManager.GetString("Constitution_TripleStars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your contact page..
        /// </summary>
        public static string Contact_Subtitle {
            get {
                return ResourceManager.GetString("Contact_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact_Title {
            get {
                return ResourceManager.GetString("Contact_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn_Title {
            get {
                return ResourceManager.GetString("LogIn_Title", resourceCulture);
            }
        }
    }
}
