//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I18N.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Event {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Event() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("I18N.Core.Event", typeof(Event).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join as a Coach.
        /// </summary>
        public static string Event_Action_JoinCoach {
            get {
                return ResourceManager.GetString("Event_Action_JoinCoach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string Event_Action_JoinMember {
            get {
                return ResourceManager.GetString("Event_Action_JoinMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        public static string Event_Action_LeaveCoach {
            get {
                return ResourceManager.GetString("Event_Action_LeaveCoach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        public static string Event_Action_LeaveMember {
            get {
                return ResourceManager.GetString("Event_Action_LeaveMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Time.
        /// </summary>
        public static string Event_Core_CreationTime {
            get {
                return ResourceManager.GetString("Event_Core_CreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string Event_Core_EndDate {
            get {
                return ResourceManager.GetString("Event_Core_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end date is required..
        /// </summary>
        public static string Event_Core_EndDateRequired {
            get {
                return ResourceManager.GetString("Event_Core_EndDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Event_Core_Level {
            get {
                return ResourceManager.GetString("Event_Core_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to choose at least one practice level..
        /// </summary>
        public static string Event_Core_LevelDateRequired {
            get {
                return ResourceManager.GetString("Event_Core_LevelDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Event_Core_Name {
            get {
                return ResourceManager.GetString("Event_Core_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name field is required..
        /// </summary>
        public static string Event_Core_NameRequired {
            get {
                return ResourceManager.GetString("Event_Core_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string Event_Core_StartDate {
            get {
                return ResourceManager.GetString("Event_Core_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start date is required..
        /// </summary>
        public static string Event_Core_StartDateRequired {
            get {
                return ResourceManager.GetString("Event_Core_StartDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an event.
        /// </summary>
        public static string Event_Create_Title {
            get {
                return ResourceManager.GetString("Event_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string Event_Delete_Dislamer {
            get {
                return ResourceManager.GetString("Event_Delete_Dislamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this event.
        /// </summary>
        public static string Event_Delete_Title {
            get {
                return ResourceManager.GetString("Event_Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Event_Details_Title {
            get {
                return ResourceManager.GetString("Event_Details_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit this event.
        /// </summary>
        public static string Event_Edit_Title {
            get {
                return ResourceManager.GetString("Event_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string Event_Index_From {
            get {
                return ResourceManager.GetString("Event_Index_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events List.
        /// </summary>
        public static string Event_Index_Title {
            get {
                return ResourceManager.GetString("Event_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string Event_Index_To {
            get {
                return ResourceManager.GetString("Event_Index_To", resourceCulture);
            }
        }
    }
}
